Repository ui5-community/bestofui5-website, pull requests merged in 2022-04, with the labels that each got.

#40 feat(frontend): set darkmode depending on oss settings
  uimodule/src/index.html
Labels: website

#43 feat(crawler): run crawler and build everyday at 6
  .github/workflows/build.yml
Labels: backend

#44 feat(crawler): read data from npm and display on page
  crawler/src/gh-repos.ts
  crawler/src/index.ts
  crawler/src/npm.ts
  crawler/src/types.d.ts
  uimodule/src/control/PackageListItemContent.control.xml
  uimodule/src/control/PackageListItemContent.ts
  uimodule/src/view/Main.view.xml
Labels: backend, website

#45 feature(frontend): sort list by downloads
  crawler/src/npm.ts
  uimodule/src/controller/Main.controller.ts
Labels: website

#46 fix: remove code
  uimodule/src/controller/Main.controller.ts
Labels: website

#52 feat(frontend): add icontab with new views and filter
  uimodule/src/Component.ts
  uimodule/src/control/PackageListItemContent.control.xml
  uimodule/src/controller/BaseController.ts
  uimodule/src/controller/IconTabHeaderControl.ts
  uimodule/src/controller/Main.controller.ts
  uimodule/src/controller/Object.controller.ts
  uimodule/src/controller/Packages.controller.ts
  uimodule/src/controller/QueryControl.ts
  uimodule/src/controller/Tags.controller.ts
  uimodule/src/manifest.json
  uimodule/src/model/data.json
  uimodule/src/view/IconTabHeader.fragment.xml
  uimodule/src/view/Main.view.xml
  uimodule/src/view/Packages.view.xml
  uimodule/src/view/Tags.view.xml
Labels: website

#54 feat: add a issue template to add a new package
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new_package.md
  uimodule/src/controller/IconTabHeaderControl.ts
  uimodule/src/view/IconTabHeader.fragment.xml
Labels: website, maintenance

#68 feat: add changelog
  CHANGELOG.md
Labels: maintenance

#69 fix(frontend): fix automatic color scheme change
  packages/ui/src/index.html
Labels: website

#72 feat: add count to tags/types and show them on frontend
  packages/crawler/src/index.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/model/data.json
  packages/ui/src/view/Tags.view.xml
Labels: backend, website

#74 Seperate types tags
  CHANGELOG.md
  packages/crawler/src/index.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/Component.ts
  packages/ui/src/controller/AllPackages.controller.ts
  packages/ui/src/controller/HotPackages.controller.ts
  packages/ui/src/controller/QueryControl.ts
  packages/ui/src/controller/Tags.controller.ts
  packages/ui/src/model/data.json
  packages/ui/src/view/IconTabHeader.fragment.xml
  packages/ui/src/view/Main.view.xml
  packages/ui/src/view/Tags.view.xml
Labels: backend, website

#70 fix(frontend): fix css on rounded toolbar
  packages/ui/src/css/style.css
  packages/ui/src/view/Main.view.xml
Labels: website

#77 feat: sort "hot packages" view by downloads growth
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/control/PackageListItemContent.control.xml
  packages/ui/src/control/PackageListItemContent.ts
  packages/ui/src/controller/HotPackages.controller.ts
  packages/ui/src/model/data.json
  packages/ui/src/view/AllPackages.view.xml
  packages/ui/src/view/HotPackages.view.xml
Labels: backend, website

#39 feat(readme): reflect current status in readme
  CHANGELOG.md
  README.md
Labels: maintenance

#79 implemented fetch of jsdoc
  packages/crawler/package.json
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/model/data.json
  yarn.lock
Labels: backend

#88 chore: updated readme/issue template
  .github/ISSUE_TEMPLATE/new_package.md
  README.md
Labels: maintenance

#90 feat(crawler): add BoUI5Types to enum
  packages/crawler/src/types.d.ts
Labels: backend

#83 feat: add wdi5
  packages/crawler/sources.json
Labels: new package

#98 fix(crawler): avoid fail crawl when no yaml file present
  packages/crawler/src/gh-repos.ts
Labels: bug, backend

#100 fix(frontend): await json model data in object view
  packages/ui/src/controller/BaseController.ts
  packages/ui/src/controller/Object.controller.ts
Labels: bug, website

#96 build: update project configuration
  .editorconfig
  .husky/pre-commit
  .husky/pre-push
  .prettierrc
  CHANGELOG.md
  package.json
  packages/crawler/.eslintrc.json
  packages/crawler/package.json
  packages/crawler/sources.json
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/index.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/crawler/tsconfig.json
  packages/ui/.babelrc.json
  packages/ui/.eslintrc.json
  packages/ui/package.json
  packages/ui/src/Component.ts
  packages/ui/src/control/CustomControlXML.gen.d.ts
  packages/ui/src/control/CustomControlXML.ts
  packages/ui/src/control/CustomControlXMLRenderer.ts
  packages/ui/src/control/PackageListItemContent.gen.d.ts
  packages/ui/src/control/PackageListItemContent.ts
  packages/ui/src/controller/AllPackages.controller.ts
  packages/ui/src/controller/App.controller.ts
  packages/ui/src/controller/BaseController.ts
  packages/ui/src/controller/HotPackages.controller.ts
  packages/ui/src/controller/Main.controller.ts
  packages/ui/src/controller/Object.controller.ts
  packages/ui/src/controller/QueryControl.ts
  packages/ui/src/controller/Tags.controller.ts
  packages/ui/src/css/style.css
  packages/ui/src/index.html
  packages/ui/src/model/data.json
  packages/ui/src/model/formatter.ts
  packages/ui/src/model/models.ts
  packages/ui/tsconfig.json
  packages/ui/ui5-dist.yaml
  tsconfig.json
  yarn.lock
Labels: maintenance

#102 fix(frontend): fix on "await on jsonmodel loaded"
  .github/workflows/build.yml
  .prettierignore
  packages/crawler/src/gh-repos.ts
  packages/ui/src/controller/BaseController.ts
  packages/ui/src/controller/Object.controller.ts
Labels: bug, website

#105 fix(frontend): add baseurl to markdown renderer for relative links
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/types.d.ts
  packages/ui/package.json
  packages/ui/src/model/data.json
  packages/ui/src/view/Object.view.xml
  yarn.lock
Labels: bug, website

#109 feat: add ui5 generator as sources
  packages/crawler/sources.json
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/index.ts
  packages/crawler/src/npm.ts
  packages/ui/src/control/PackageListItemContent.control.xml
  packages/ui/src/css/style.css
  packages/ui/src/model/data.json
  packages/ui/src/view/HotPackages.view.xml
  packages/ui/src/view/Main.view.xml
  packages/ui/src/view/Object.view.xml
Labels: enhancement, website

#110 feat(frontend): remove margin on readme subsection
  packages/ui/src/css/style.css
Labels: enhancement, website

#114 feat: change growth indicator from month to fortnight
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/control/PackageListItemContent.control.xml
  packages/ui/src/control/PackageListItemContent.ts
  packages/ui/src/model/data.json
  packages/ui/src/view/AllPackages.view.xml
  packages/ui/src/view/HotPackages.view.xml
Labels: enhancement, backend, website

#116 feat(crawler): get updatedAt from latest commit
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/model/data.json
Labels: enhancement, backend

#117 feat(crawler): refactor typescript
  packages/crawler/src/Package.ts
  packages/crawler/src/gh-repos.ts
  packages/crawler/src/index.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/model/data.json
Labels: enhancement, backend

#118 feat(crawler): use npm bulk api for downloads
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
Labels: enhancement, backend

#119 feat(crawler): get npm downloads history
  packages/crawler/src/Package.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/model/data.json
Labels: enhancement, backend

#122 feat(frontend): show relevant data on sorting
  packages/ui/src/control/PackageListItemContent.control.xml
  packages/ui/src/control/PackageListItemContent.ts
  packages/ui/src/i18n/i18n_en.properties
  packages/ui/src/view/AllPackages.view.xml
Labels: enhancement, website

#120 feat(frontend): show npm downloads history on object page
  packages/ui/package.json
  packages/ui/src/control/BarChart.gen.d.ts
  packages/ui/src/control/BarChart.ts
  packages/ui/src/control/ChartRecord.gen.d.ts
  packages/ui/src/control/ChartRecord.ts
  packages/ui/src/control/CustomControlXML.ts
  packages/ui/src/controller/App.controller.ts
  packages/ui/src/controller/Main.controller.ts
  packages/ui/src/controller/Object.controller.ts
  packages/ui/src/css/style.css
  packages/ui/src/manifest.json
  packages/ui/src/view/App.view.xml
  packages/ui/src/view/Object.view.xml
  packages/ui/tsconfig.json
  packages/ui/ui5.yaml
  yarn.lock
Labels: enhancement, website

#126 fix(frontend): fix removal of Main.view
  packages/ui/src/controller/AllPackages.controller.ts
  packages/ui/src/controller/BaseController.ts
  packages/ui/src/controller/HotPackages.controller.ts
  packages/ui/src/controller/Object.controller.ts
  packages/ui/src/controller/Tags.controller.ts
  packages/ui/src/view/HotPackages.view.xml
Labels: bug, website

#127 feat(frontend): add timeline with version from npm
  .github/workflows/build.yml
  packages/crawler/src/Package.ts
  packages/crawler/src/index.ts
  packages/crawler/src/npm.ts
  packages/crawler/src/types.d.ts
  packages/ui/src/controller/Timeline.controller.ts
  packages/ui/src/manifest.json
  packages/ui/src/model/data.json
  packages/ui/src/model/versions.json
  packages/ui/src/view/IconTabHeader.fragment.xml
  packages/ui/src/view/Timeline.view.xml
  packages/ui/ui5.yaml
Labels: enhancement, website

#130 fix: add config.yml file
  _config.yml
  packages/ui/src/_config.yml
Labels: bug

#131 fix: run scheduled gh action earlier to avoid delay
  .github/workflows/build.yml
Labels: bug, maintenance

#113 fix(frontend): remove theme from build
  packages/ui/src/index.html
  packages/ui/ui5.yaml
Labels: enhancement, website

#136 feat(ui): add cname
  packages/ui/src/CNAME
Labels: enhancement, website

#137 feat(ui): change filter to AND
  packages/ui/src/controller/QueryControl.ts
Labels: enhancement, website

#138 fix(ui): set selected header key in timeline
  packages/ui/src/controller/Timeline.controller.ts
Labels: bug, website

#139 fix(ui): wrap text in markdown
  packages/ui/src/css/style.css
  packages/ui/src/view/Object.view.xml
Labels: bug, website

#140 fix(ui): fix sorting on all
  packages/ui/src/view/AllPackages.view.xml
  packages/ui/src/view/Object.view.xml
Labels: bug, website

#141 feat(ui): add new icons and add them to view
  .prettierignore
  packages/ui/.eslintrc.json
  packages/ui/src/Component.ts
  packages/ui/src/control/PackageListItemContent.control.xml
  packages/ui/src/control/PackageListItemContent.ts
  packages/ui/src/font-awesome/brands.js
  packages/ui/src/font-awesome/brands.min.css
  packages/ui/src/font-awesome/fa-brands.js
  packages/ui/src/font-awesome/fa-brands.json
  packages/ui/src/font-awesome/fa-brands.ttf
  packages/ui/src/font-awesome/fa-brands.woff2
  packages/ui/src/font-awesome/font.css
  packages/ui/src/font-awesome/github.svg
  packages/ui/src/font-awesome/npm.svg
  packages/ui/src/manifest.json
  packages/ui/src/view/IconTabHeader.fragment.xml
  packages/ui/src/view/Object.view.xml
Labels: enhancement, website

#145 fix: fix links to new repo name and change namespace
  .github/ISSUE_TEMPLATE/new_package.md
  README.md
  package.json
  packages/ui/src/Component.ts
  packages/ui/src/control/BarChart.ts
  packages/ui/src/control/ChartRecord.ts
  packages/ui/src/control/CustomControlXML.ts
  packages/ui/src/control/CustomControlXMLRenderer.ts
  packages/ui/src/control/PackageListItemContent.ts
  packages/ui/src/controller/AllPackages.controller.ts
  packages/ui/src/controller/App.controller.ts
  packages/ui/src/controller/BaseController.ts
  packages/ui/src/controller/HotPackages.controller.ts
  packages/ui/src/controller/Object.controller.ts
  packages/ui/src/controller/Tags.controller.ts
  packages/ui/src/controller/Timeline.controller.ts
  packages/ui/src/i18n/i18n.properties
  packages/ui/src/i18n/i18n_en.properties
  packages/ui/src/index.html
  packages/ui/src/manifest.json
  packages/ui/src/view/AllPackages.view.xml
  packages/ui/src/view/App.view.xml
  packages/ui/src/view/HotPackages.view.xml
  packages/ui/src/view/IconTabHeader.fragment.xml
  packages/ui/src/view/Object.view.xml
  packages/ui/src/view/Tags.view.xml
  packages/ui/src/view/Timeline.view.xml
Labels: bug, website

#146 fix(ui): change icontabheader to buttons for overflow
  README.md
  packages/ui/src/Component.ts
  packages/ui/src/controller/AllPackages.controller.ts
  packages/ui/src/controller/App.controller.ts
  packages/ui/src/controller/BaseController.ts
  packages/ui/src/controller/Tags.controller.ts
  packages/ui/src/controller/Timeline.controller.ts
  packages/ui/src/view/App.view.xml
  packages/ui/src/view/IconTabHeader.fragment.xml
  packages/ui/src/view/LinkHeader.fragment.xml
Labels: bug, website

#152 fix(ui): remove padding on chart
  packages/ui/src/control/BarChart.ts
Labels: bug, website

#150 feat(ui): introduce splash screen
  packages/crawler/.prettierignore
  packages/ui/.prettierignore
  packages/ui/src/Component.ts
  packages/ui/src/img/B_UI5_V.svg
  packages/ui/src/img/O_UI5_V.svg
  packages/ui/src/index.html
Labels: enhancement, website

#160 fix(ui): fix font-awesome loading
  .gitignore
  packages/ui/src/Component.ts
  packages/ui/src/font-awesome/font.css
Labels: bug, website

#169 feat(ui): improve chart and object page
  src/control/BarChart.ts
  src/css/style.css
  src/view/Object.view.xml
Labels: enhancement, website

#173 feat(i18n): convert string to i18n
  package-lock.json
  src/i18n/i18n.properties
  src/i18n/i18n_en.properties
  src/view/AllPackages.view.xml
  src/view/App.view.xml
  src/view/HotPackages.view.xml
  src/view/LinkHeader.fragment.xml
  src/view/Object.view.xml
  src/view/Tags.view.xml
Labels: enhancement

#175 feat(test): add basic test setup with workflow
  .eslintignore
  .github/workflows/wdi5-test.yml
  babel.config.js
  package-lock.json
  package.json
  src/test/e2e/basics.test.js
  src/test/e2e/pageObjects/All.js
  src/test/e2e/pageObjects/Main.js
  src/test/e2e/pageObjects/Page.js
  wdio.conf.js
Labels: enhancement

#177 chore: update readme
  README.md
  src/view/App.view.xml
Labels: maintenance

#174 feat(seo): add metadata, description and titles
  src/Component.ts
  src/i18n/i18n_en.properties
  src/img/B_UI5_V.png
  src/index.html
  src/test/e2e/basics.test.js
  src/view/App.view.xml
Labels: enhancement
